#scraped stats dataframe changes

{'AC Milan': 'ACMilan', 'Amiens': 'Amiens', 'Angers':'Angers',
 'Arsenal':'Arsenal','Atalanta':'Atalanta', 'Athletic Bilbao': 'AthleticBilbao',
 'Atletico Madrid': 'AtleticoMadrid', 'Augsburg':'Augsburg', 'Barcelona':'Barcelona',
 'Bayer Leverkusen': 'BayerLeverkusen', 'Bayern Munich':'BayernMunich',
 'Bologna':'Bologna', 'Bordeaux':'Bordeaux', 'Borussia Dortmund':'BorussiaDortmund',
 'Borussia M.Gladbach': 'BorussiaMonchengladbach', 'Bournemouth':'Bournemouth',
 'Brighton':'Brighton', 'Burnley':'Burnley', 'Caen':'Caen', 'Cagliari':'Cagliari',
 'Cardiff':'Cardiff', 'Celta Vigo':'CeltaVigo', 'Chelsea':'Chelsea','Chievo':'Chievo',
 'Crystal Palace':'CrystalPalace','Deportivo Alaves':'DeportivoAlaves',
 'Dijon':'Dijon', 'Eibar':'Eibar', 'Eintracht Frankfurt':'EintrachtFrankfurt',
 'Empoli':'Empoli', 'Espanyol':'Espanyol', 'Everton':'Everton', 'Fiorentina':'Fiorentina',
 'Fortuna Duesseldorf':'FortunaDuesseldorf', 'Freiburg':'Freiburg', 'Frosinone':'Frosinone',
 'Fulham':'Fulham', 'Genoa':'Genoa','Getafe':'Getafe', 'Girona':'Girona',
 'Guingamp':'Guingamp', 'Hannover 96':'Hannover96', 'Hertha Berlin':'HerthaBerlin',
 'Hoffenheim':'Hoffenheim', 'Huddersfield':'Huddersfield', 'Inter':'InterMilan',
 'Juventus':'Juventus', 'Lazio':'Lazio', 'Leganes':'Leganes', 'Leicester':'Leicester',
 'Levante':'Levante', 'Lille':'Lille','Liverpool':'Liverpool','Lyon':'Lyon',
 'Mainz 05': 'Mainz05','Manchester City':'ManchesterCity','Manchester United':'ManchesterUnited',
 'Marseille':'Marseille','Monaco':'Monaco','Montpellier':'Montpellier','Nantes':'Nantes',
 'Napoli':'Napoli', 'Newcastle United':'NewcastleUnited','Nice':'Nice','Nimes':'Nimes',
 'Nuernberg':'Nuernberg','Paris Saint-Germain':'PSG', 'Parma Calcio 1913':'Parma',
 'RasenBallsport Leipzig':'RBLeipzig', 'Rayo Vallecano':'RayoVallecano',
 'Real Betis':'RealBetis', 'Real Madrid':'RealMadrid','Real Sociedad':'RealSociedad',
 'Real Valladolid':'Real Valladolid', 'Reims':'Reims','Rennes':'Rennes','Roma':'Roma',
 'SD Huesca':'Huesca','SPAL 2013':'SPAL', 'Saint-Etienne':'SaintEtienne',
 'Sampdoria':'Sampdoria','Sassuolo':'Sassuolo','Schalke 04':'Schalke',
 'Sevilla':'Sevilla', 'Southampton':'Southampton', 'Strasbourg':'Strasbourg',
 'Torino':'Torino','Tottenham':'Tottenham','Toulouse':'Toulouse','Udinese':'Udinese',
 'Valencia':'Valencia', 'VfB Stuttgart':'Stuttgart','Villareal':'Villareal',
 'Watford':'Watford','Werder Bremen':'WerderBremen','West Ham':'WestHam',
 'Wolfsburg':'Wolfsburg','Wolverhampton Wanderers':'Wolves'}

#fifa dataframe changes
{'Milan':'ACMilan', 'Amiens SC': 'Amiens', 'Angers SCO': 'Angers',
'Arsenal':'Arsenal','Atalanta':'Atalanta', 'Athletic Club de Bilbao': 'AthleticBilbao',
'Atletico Madrid': 'AtleticoMadrid', 'FC Augsburg':'Augsburg', 'FC Barcelona':'Barcelona',
 'Bayer 04 Leverkusen': 'BayerLeverkusen', 'FC Bayern Munchen':'BayernMunich',
 'Bologna':'Bologna', 'FC Girondins de Bordeaux':'Bordeaux','Borussia Dortmund':'BorussiaDortmund',
 'Borussia Monchengladbach':'BorussiaMonchengladbach', 'Bournemouth':'Bournemouth',
 'Brighton & Hove Albion':'Brighton', 'Burnley':'Burnley', 'Stade Malherbe Caen':'Caen',
 'Cagliari':'Cagliari', 'Cardiff City':'Cardiff', 'RC Celta':'CeltaVigo','Chelsea':'Chelsea',
 'Chievo Verona':'Chievo', 'Crystal Palace':'CrystalPalace', 'Deportivo Alaves':'DeportivoAlaves',
 'Dijon FCO':'Dijon', 'SD Eibar':'Eibar', 'Eintracht Frankfurt':'EintrachtFrankfurt',
 'Empoli':'Empoli', 'RCD Espanyol':'Espanyol', 'Everton':'Everton', 'Fiorentina':'Fiorentina',
 'Fortuna Duesseldorf':'FortunaDuesseldorf', 'SC Freiburg':'Freiburg', 'Frosinone':'Frosinone',
 'Fulham':'Fulham','Genoa':'Genoa', 'Getafe CF':'Getafe', 'Girona FC':'Girona',
 'En Avant de Guingamp':'Guingamp', 'Hannover 96':'Hannover96', 'Hertha BSC':'HerthaBerlin',
 'TSG 1899 Hoffenheim':'Hoffenheim', 'Huddersfield Town':'Huddersfield', 'Inter':'InterMilan',
 'Juventus':'Juventus', 'Lazio':'Lazio', 'CD Leganes':'Leganes', 'Leicester City':'Leicester',
 'Levante UD':'Levante', 'LOSC Lille':'Lille', 'Liverpool':'Liverpool', 'Olympique Lyonnais':'Lyon',
 '1. FSV Mainz 05': 'Mainz05', 'Manchester City':'ManchesterCity', 'Manchester United':'ManchesterUnited',
 'Olympique de Marseille':'Marseille', 'AS Monaco':'Monaco', 'Montpellier HSC':'Montpellier',
 'FC Nantes':'Nantes', 'Napoli':'Napoli', 'Newcastle United':'NewcastleUnited', 'OGC Nice':'Nice',
 'Nimes Olympique':'Nimes','1. FC Nurnberg':'Nuernberg', 'Paris Saint-Germain':'PSG',
 'Parma':'Parma', 'RB Leipzig':'RBLeipzig','Rayo Vallecano':'RayoVallecano',
 'Real Betis':'RealBetis', 'Real Madrid':'RealMadrid','Real Sociedad':'RealSociedad',
 'Real Valladolid CF':'Real Valladolid', 'Stade de Reims':'Reims', 'Stade Rennais FC':'Rennes',
 'Roma':'Roma','SD Huesca':'Huesca','SPAL':'SPAL', 'AS Saint-Etienne':'SaintEtienne',
 'Sampdoria':'Sampdoria','Sassuolo':'Sassuolo','FC Schalke 04':'Schalke',
 'Sevilla FC':'Sevilla', 'Southampton':'Southampton','RC Strasbourg Alsace':'Strasbourg',
 'Torino':'Torino','Tottenham Hotspur':'Tottenham','Toulouse Football Club':'Toulouse',
 'Udinese':'Udinese','Valencia CF':'Valencia', 'VfB Stuttgart':'Stuttgart','Villareal CF':'Villareal',
 'Watford':'Watford','SV Werder Bremen':'WerderBremen','West Ham United':'WestHam',
 'VfL Wolfsburg':'Wolfsburg','Wolverhampton Wanderers':'Wolves'}
